# must do conda install -c NostrumBioDiscovery pele_platform 
package:
  name: pele_platform
  version: "1.3.4"

about:
  home: https://github.com/nostrumbiodiscovery/pele_platform
  license: Apache
  license_file: LICENSE
  summary: Automatic platform to spawn PELE, AdaptivePELE, MSM_PELE ad frag_PELE jobs

source:
  path: ../

build:
  script: python -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python

  run:
    # Base dependencies
    - python
    - numpy
    - matplotlib
    - scipy
    - pandas
    - pytest
    - adaptive_pele
    - pyyaml
    - pppele
    - fpdf
    - scikit-learn
    - rdkit

test:
  imports:
    - pele_platform
  command:
    - python -m pele_platform.main -h 
